package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/akafazov/gqlgen/graph/model"
)

// Description is the resolver for the description field.
func (r *meetupResolver) Description(ctx context.Context, obj *model.Meetup) (string, error) {
	panic(fmt.Errorf("not implemented: Description - description"))
}

// Meetups is the resolver for the meetups field.
func (r *queryResolver) Meetups(ctx context.Context) ([]*model.Meetup, error) {
	panic(fmt.Errorf("not implemented: Meetups - meetups"))
}

// Meetup returns MeetupResolver implementation.
func (r *Resolver) Meetup() MeetupResolver { return &meetupResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type meetupResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
