package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/akafazov/gqlgen/graph/model"
)

var users = []*model.User{
	{
		ID:       "1",
		Username: "user1",
		Email:    "user1@gmail.com",
		Meetups:  []*model.Meetup{},
	},
	{
		ID:       "2",
		Username: "user2",
		Email:    "user2@gmail.com",
		Meetups:  []*model.Meetup{},
	},
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	return users, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
