package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/akafazov/gqlgen/graph/model"
)

// Angels is the resolver for the angels field.
func (r *queryResolver) Angels(ctx context.Context) ([]*model.Angel, error) {
	panic(fmt.Errorf("not implemented: Angels - angels"))
}
