package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/akafazov/gqlgen/graph/model"
)

var meetups = []*model.Meetup{
	{
		ID:          "1",
		Name:        "meetup1",
		Description: "description1",
		User:        users[0],
	},
	{
		ID:          "2",
		Name:        "meetup2",
		Description: "description2",
		User:        users[1],
	},
}

// Description is the resolver for the description field.
func (r *meetupResolver) Description(ctx context.Context, obj *model.Meetup) (string, error) {
	if obj == nil {
		return "", fmt.Errorf("meetup is nil")
	}
	return obj.Description, nil
}

// Meetups is the resolver for the meetups field.
func (r *queryResolver) Meetups(ctx context.Context) ([]*model.Meetup, error) {
	return meetups, nil
}

// Meetup returns MeetupResolver implementation.
func (r *Resolver) Meetup() MeetupResolver { return &meetupResolver{r} }

type meetupResolver struct{ *Resolver }
