// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Angel struct {
	ID string `json:"id"`
}

type Meetup struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	User        *User  `json:"user"`
}

type Query struct {
}
