name: ci
on: [push]
  workflow_call:
    outputs:
      version:
        description: "The created Version"
        value: ${{ jobs.createVersion.outputs.version }}


jobs:
  createVersion:
    uses: openmfp/gha/.github/workflows/job-create-version.yml
    secrets: inherit
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    uses: openmfp/gha/.github/workflows/pipeline-golang-module.yml@main
    secrets: inherit
    with:
      useLocalCoverageConfig: true
      coverageThreasholdFile: 0
      coverageThreasholdPackage: 0
      coverageThreasholdTotal: 0
