name: ci
on: [push]

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    uses: darashevcstbg/gqlgen/.github/workflows/pipeline-golang-module.yml@main
    secrets: inherit
    with:
      useLocalCoverageConfig: true